'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BatchRunning
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property CreateDate As Date
    Public Property CreateBy As String

End Class
