'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Company
    Public Property Id As Integer
    Public Property Code As String
    Public Property Name As String
    Public Property Address As String
    Public Property Tel As String
    Public Property Fax As String
    Public Property Email As String
    Public Property TaxNo As String
    Public Property Description As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

    Public Overridable Property Locations As ICollection(Of Locations) = New HashSet(Of Locations)
    Public Overridable Property Products As ICollection(Of Products) = New HashSet(Of Products)
    Public Overridable Property RcvHeader As ICollection(Of RcvHeader) = New HashSet(Of RcvHeader)
    Public Overridable Property Zone As ICollection(Of Zone) = New HashSet(Of Zone)
    Public Overridable Property Users As ICollection(Of Users) = New HashSet(Of Users)

End Class
