'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CurrentStocks
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property FKOwner As Integer
    Public Property FKWarehouse As Integer
    Public Property FKVendor As Integer
    Public Property FKLocation As Integer
    Public Property FKProduct As Integer
    Public Property Qty As Decimal
    Public Property BookQty As Decimal
    Public Property PriceUnit As Decimal
    Public Property NetPrice As Decimal
    Public Property FKProductUnit As Integer
    Public Property LotNo As String
    Public Property ProductDate As Date
    Public Property ExpDate As Date
    Public Property ReceiveDate As Date
    Public Property FKItemStatus As Integer
    Public Property PalletCode As String
    Public Property ACCTASSCAT As String
    Public Property SourceConfirm As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property CheckBy As String
    Public Property CheckDate As Nullable(Of Date)
    Public Property Enable As Boolean

    Public Overridable Property ItemStatus As ItemStatus
    Public Overridable Property Locations As Locations
    Public Overridable Property Owners As Owners
    Public Overridable Property Products As Products
    Public Overridable Property ProductUnit As ProductUnit
    Public Overridable Property Vendor As Vendor
    Public Overridable Property Warehouse As Warehouse

End Class
