'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CycleCountHD
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property FKWarehouse As Integer
    Public Property FKOwner As Integer
    Public Property DocNo As String
    Public Property DocDate As Date
    Public Property Description As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

    Public Overridable Property CycleCountDTL As ICollection(Of CycleCountDTL) = New HashSet(Of CycleCountDTL)
    Public Overridable Property Owners As Owners
    Public Overridable Property Warehouse As Warehouse

End Class
