'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GoodsIssueOrderDetails
    Public Property Description As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean
    Public Property WmsNo As String
    Public Property SDDoc As String
    Public Property SapStatus As String
    Public Property MsgTy As String
    Public Property MsgId As String
    Public Property MsgNo As String
    Public Property Message As String
    Public Property Id As Integer
    Public Property FKGoodsIssueOrder As Integer

End Class
