'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IssueSum
    Public Property Id As Integer
    Public Property BatchNo As String
    Public Property FKTransport As Nullable(Of Integer)
    Public Property FKPickingType As Integer
    Public Property FKCompany As Integer
    Public Property FKOwner As Integer
    Public Property FKProduct As Integer
    Public Property Qty As Decimal
    Public Property Amt As Decimal
    Public Property FKWarehouse As Integer
    Public Property FKItemStatus As Integer
    Public Property Remark As String
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

    Public Overridable Property ItemStatus As ItemStatus
    Public Overridable Property Owners As Owners
    Public Overridable Property PickingType As PickingType
    Public Overridable Property Products As Products
    Public Overridable Property Transports As Transports
    Public Overridable Property Warehouse As Warehouse
    Public Overridable Property PickLocation As ICollection(Of PickLocation) = New HashSet(Of PickLocation)

End Class
