'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Locations
    Public Property Id As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property FKCompany As Integer
    Public Property FKZone As Integer
    Public Property FKLocationType As Integer
    Public Property FKWarehouse As Integer
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean
    Public Property InStorage As Boolean
    Public Property AutoReceive As Boolean

    Public Overridable Property Company As Company
    Public Overridable Property CheckStockLocation As ICollection(Of CheckStockLocation) = New HashSet(Of CheckStockLocation)
    Public Overridable Property CurrentStocks As ICollection(Of CurrentStocks) = New HashSet(Of CurrentStocks)
    Public Overridable Property CycleCountDTL As ICollection(Of CycleCountDTL) = New HashSet(Of CycleCountDTL)
    Public Overridable Property LocationType As LocationType
    Public Overridable Property Warehouse As Warehouse
    Public Overridable Property Zone As Zone
    Public Overridable Property RcvLocation As ICollection(Of RcvLocation) = New HashSet(Of RcvLocation)
    Public Overridable Property TransferDTL As ICollection(Of TransferDTL) = New HashSet(Of TransferDTL)
    Public Overridable Property PickLocation As ICollection(Of PickLocation) = New HashSet(Of PickLocation)

End Class
