'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Owners
    Public Property Id As Integer
    Public Property Code As String
    Public Property Name As String
    Public Property Address As String
    Public Property Tel As String
    Public Property Fax As String
    Public Property Email As String
    Public Property TaxNo As String
    Public Property Description As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean
    Public Property FKCompany As Integer

    Public Overridable Property OwnerAccess As ICollection(Of OwnerAccess) = New HashSet(Of OwnerAccess)
    Public Overridable Property TravelFee As ICollection(Of TravelFee) = New HashSet(Of TravelFee)
    Public Overridable Property CheckStockLocation As ICollection(Of CheckStockLocation) = New HashSet(Of CheckStockLocation)
    Public Overridable Property CurrentStocks As ICollection(Of CurrentStocks) = New HashSet(Of CurrentStocks)
    Public Overridable Property Customers As ICollection(Of Customers) = New HashSet(Of Customers)
    Public Overridable Property CycleCountHD As ICollection(Of CycleCountHD) = New HashSet(Of CycleCountHD)
    Public Overridable Property IssueSum As ICollection(Of IssueSum) = New HashSet(Of IssueSum)
    Public Overridable Property LabelLog As ICollection(Of LabelLog) = New HashSet(Of LabelLog)
    Public Overridable Property MaterialTrans As ICollection(Of MaterialTrans) = New HashSet(Of MaterialTrans)
    Public Overridable Property PhyCountHD As ICollection(Of PhyCountHD) = New HashSet(Of PhyCountHD)
    Public Overridable Property Products As ICollection(Of Products) = New HashSet(Of Products)
    Public Overridable Property RcvHeader As ICollection(Of RcvHeader) = New HashSet(Of RcvHeader)
    Public Overridable Property StockOnhand As ICollection(Of StockOnhand) = New HashSet(Of StockOnhand)
    Public Overridable Property PickOrderHD As ICollection(Of PickOrderHD) = New HashSet(Of PickOrderHD)

End Class
