'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PickOrderHD
    Public Property Id As Integer
    Public Property SrcName As String
    Public Property InterfaceName As String
    Public Property OrderNo As String
    Public Property OrderDate As Date
    Public Property Description As String
    Public Property RefNo As String
    Public Property RefDate As Nullable(Of Date)
    Public Property BatchNo As String
    Public Property FKCostCenter As Nullable(Of Integer)
    Public Property PickingDate As Date
    Public Property FKTransport As Integer
    Public Property FKPickingType As Integer
    Public Property FKCompany As Integer
    Public Property FKOwner As Integer
    Public Property FKCustomer As Integer
    Public Property TotalQty As Decimal
    Public Property TotalAmt As Decimal
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property PickedDate As Nullable(Of Date)
    Public Property PickedBy As String
    Public Property PDAPickedDate As Nullable(Of Date)
    Public Property PDAPickedBy As String
    Public Property PostGIDate As Nullable(Of Date)
    Public Property PostGIBy As String
    Public Property TransferInDate As Nullable(Of Date)
    Public Property TransferInBy As String
    Public Property InsertToCDBDate As Nullable(Of Date)
    Public Property IssType As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean
    Public Property SelectUse As String

    Public Overridable Property CostCenter As CostCenter
    Public Overridable Property Customers As Customers
    Public Overridable Property Owners As Owners
    Public Overridable Property PickingType As PickingType
    Public Overridable Property PickOrderDTL As ICollection(Of PickOrderDTL) = New HashSet(Of PickOrderDTL)
    Public Overridable Property Transports As Transports

End Class
