'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PickTempOrderHD
    Public Property Id As Integer
    Public Property TXLL_ID As Integer
    Public Property SRC_NAME As String
    Public Property TARGET_NAME As String
    Public Property COMP_CODE As String
    Public Property DOCUMENTNO As String
    Public Property DOCUMENTDATE As String
    Public Property DESCRIPTION As String
    Public Property PICKINGTYPECODE As String
    Public Property VENDORCODE As String
    Public Property CUSTOMERCODE As String
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property InterfaceName As String
    Public Property HeaderID As Nullable(Of Integer)
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

End Class
