'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PickOrderDTL
    Public Property Id As Integer
    Public Property FKPickOrderHD As Integer
    Public Property FKProductDetail As Integer
    Public Property Qty As Decimal
    Public Property QtyConfirm As Decimal
    Public Property QtyCheck As Decimal
    Public Property QtyLoad As Decimal
    Public Property UnitPrice As Decimal
    Public Property Amt As Decimal
    Public Property FKIOMaster As Nullable(Of Integer)
    Public Property ItemNo As String
    Public Property ItemCate As String
    Public Property FKWarehouse As Integer
    Public Property FKItemStatus As Integer
    Public Property Remark As String
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property GIDate As Nullable(Of Date)
    Public Property GIBy As String
    Public Property InterfaceName As String
    Public Property Func As String
    Public Property PLANT As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

    Public Overridable Property IOMaster As IOMaster
    Public Overridable Property ItemStatus As ItemStatus
    Public Overridable Property Warehouse As Warehouse
    Public Overridable Property ProductDetails As ProductDetails
    Public Overridable Property PickTote As ICollection(Of PickTote) = New HashSet(Of PickTote)
    Public Overridable Property PickOrderHD As PickOrderHD

End Class
