'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PickLocation
    Public Property Id As Integer
    Public Property FKIssueSum As Integer
    Public Property FKCompany As Integer
    Public Property FKLocation As Integer
    Public Property ProductDate As Nullable(Of Date)
    Public Property ExpDate As Nullable(Of Date)
    Public Property ReceiveDate As Nullable(Of Date)
    Public Property FKVendor As Nullable(Of Integer)
    Public Property Qty As Decimal
    Public Property Amt As Decimal
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property AssignDate As Nullable(Of Date)
    Public Property AssingBy As String
    Public Property PickBy As String
    Public Property GIDate As Nullable(Of Date)
    Public Property GIBy As String
    Public Property CurStockID As Nullable(Of Integer)
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean
    Public Property PickingUse As String
    Public Property PickingUsed As Nullable(Of Boolean)

    Public Overridable Property IssueSum As IssueSum
    Public Overridable Property Locations As Locations

End Class
