'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PickTote
    Public Property Id As Integer
    Public Property FKPickOrderDTL As Integer
    Public Property ToteCode As String
    Public Property ToteNo As Nullable(Of Integer)
    Public Property Qty As Decimal
    Public Property QtyLoad As Decimal
    Public Property PrintDate As Nullable(Of Date)
    Public Property PrintBy As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

    Public Overridable Property PickOrderDTL As PickOrderDTL

End Class
