'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RcvDetails
    Public Property Id As Integer
    Public Property FKRcvHeader As Integer
    Public Property FKWarehouse As Integer
    Public Property FKProductDetail As Integer
    Public Property POITEM As String
    Public Property FKItemStatus As Integer
    Public Property Quantity As Decimal
    Public Property PriceUnit As Decimal
    Public Property NetPrice As Decimal
    Public Property LotNo As String
    Public Property ProductDate As Date
    Public Property ExpDate As Date
    Public Property FKLocation As Nullable(Of Integer)
    Public Property Location As String
    Public Property PalletNo As Nullable(Of Integer)
    Public Property Remark As String
    Public Property DeliveryDate As Nullable(Of Date)
    Public Property ACCTASSCAT As String
    Public Property ITEMCATE As String
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

    Public Overridable Property ItemStatus As ItemStatus
    Public Overridable Property ProductDetails As ProductDetails
    Public Overridable Property RcvHeader As RcvHeader
    Public Overridable Property Warehouse As Warehouse

End Class
