'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RcvLocation
    Public Property Id As Integer
    Public Property FKRcvHeader As Integer
    Public Property FKWarehouse As Integer
    Public Property FKProductDetail As Integer
    Public Property FKItemStatus As Integer
    Public Property FKLocation As Integer
    Public Property PalletNo As Integer
    Public Property PalletCode As String
    Public Property Quantity As Decimal
    Public Property BaseQty As Decimal
    Public Property PriceUnit As Decimal
    Public Property NetPrice As Decimal
    Public Property LotNo As String
    Public Property ProductDate As Date
    Public Property ExpDate As Date
    Public Property Remark As String
    Public Property ACCTASSCAT As String
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property CheckDate As Nullable(Of Date)
    Public Property CheckBy As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

    Public Overridable Property ItemStatus As ItemStatus
    Public Overridable Property Locations As Locations
    Public Overridable Property ProductDetails As ProductDetails
    Public Overridable Property RcvHeader As RcvHeader
    Public Overridable Property Warehouse As Warehouse

End Class
