'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RcvTempHeader
    Public Property Id As Integer
    Public Property TXLL_ID As Integer
    Public Property SRC_NAME As String
    Public Property TARGET_NAME As String
    Public Property DELETE_IND As String
    Public Property PO_NUMBER As String
    Public Property COMP_CODE As String
    Public Property DOC_TYPE As String
    Public Property VENDOR As String
    Public Property DOCUMENT_NO As String
    Public Property DOC_DATE As String
    Public Property REF_1 As String
    Public Property OUR_REF As String
    Public Property HeaderID As Nullable(Of Integer)
    Public Property TargetType As String
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property CompleteDate As Nullable(Of Date)
    Public Property CompleteBy As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

End Class
