'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RcvTempDetail
    Public Property Id As Integer
    Public Property TXLL_ID As Integer
    Public Property SRC_NAME As String
    Public Property TARGET_NAME As String
    Public Property DELETE_IND As String
    Public Property NO_MORE_GR As String
    Public Property DOCUMENT_NO As String
    Public Property PO_REF As String
    Public Property PO_ITEM As String
    Public Property MATERIAL As String
    Public Property MATERIAL_TEXT As String
    Public Property PLANT As String
    Public Property STGE_LOC As String
    Public Property MATL_GROUP As String
    Public Property QUANTITY As Decimal
    Public Property QTY_CONFIRM As Decimal
    Public Property QTY_CONFIRMED As Decimal
    Public Property PO_UNIT As String
    Public Property NET_PRICE As Decimal
    Public Property NET_CONFIRM As Decimal
    Public Property PRICE_UNIT As Decimal
    Public Property DELIVERY_DATE3 As String
    Public Property ACCTASSCAT As String
    Public Property ITEMCATE As String
    Public Property CLOSE_STATUS As Boolean
    Public Property FKHeaderID As Nullable(Of Integer)
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

End Class
