'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RcvTempSetPallet
    Public Property RowId As Integer
    Public Property RcvHeaderId As Integer
    Public Property RcvDtlId As Nullable(Of Integer)
    Public Property RefNo As String
    Public Property RefDate As String
    Public Property FKCompany As Integer
    Public Property FKRcvType As Integer
    Public Property FKOwner As Integer
    Public Property POITEM As String
    Public Property FKItemStatus As Integer
    Public Property FKWarehouse As Integer
    Public Property FKProductDetail As Integer
    Public Property MATERIAL As String
    Public Property MATERIAL_TEXT As String
    Public Property BARCODE As String
    Public Property UNIT As String
    Public Property QUANTITY As Decimal
    Public Property PriceUnit As Decimal
    Public Property NetPrice As Decimal
    Public Property ProductDate As Date
    Public Property ExpDate As Date
    Public Property PALLET As Integer
    Public Property MAKE_FLAG As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String

End Class
