'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD007CancelGIGR
    Public Property Id As Integer
    Public Property IfId As Integer
    Public Property SrcName As String
    Public Property TargetName As String
    Public Property CompCode As String
    Public Property DocRef As String
    Public Property DoDate As String
    Public Property DoDoc As String
    Public Property Material As String
    Public Property BaseQty As Integer
    Public Property BaseUnit As String
    Public Property Func As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

End Class
