'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD004HD
    Public Property Id As Integer
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property DocRefQty As Integer

    Public Overridable Property SD004Dtl As ICollection(Of SD004Dtl) = New HashSet(Of SD004Dtl)

End Class
