'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StockOnhand
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property FKWarehouse As Integer
    Public Property FKOwner As Integer
    Public Property FKProduct As Integer
    Public Property Qty As Decimal
    Public Property QtyCost As Decimal
    Public Property NetPrice As Decimal
    Public Property BookQty As Decimal
    Public Property FKItemStatus As Integer
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

    Public Overridable Property ItemStatus As ItemStatus
    Public Overridable Property Owners As Owners
    Public Overridable Property Products As Products
    Public Overridable Property Warehouse As Warehouse

End Class
