'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StockCard
    Public Property Id As Integer
    Public Property TransactionDate As Date
    Public Property DocNo As String
    Public Property DocDate As Date
    Public Property Reference As String
    Public Property Description As String
    Public Property FKCompany As Integer
    Public Property FKWarehouse As Integer
    Public Property FKOwner As Integer
    Public Property FKProduct As Integer
    Public Property InQty As Decimal
    Public Property InCost As Decimal
    Public Property InValue As Decimal
    Public Property OutQty As Decimal
    Public Property OutCost As Decimal
    Public Property OutValue As Decimal
    Public Property BalQty As Decimal
    Public Property BalCost As Decimal
    Public Property BalValue As Decimal
    Public Property FKItemStatus As Integer
    Public Property CostCenter As String
    Public Property IOCode As String
    Public Property TransType As String
    Public Property CustCode As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property Enable As Boolean

End Class
