'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TransferDTL
    Public Property Id As Integer
    Public Property FKHD As Integer
    Public Property FKLocationSrc As Integer
    Public Property LocationTo As String
    Public Property FKProduct As Integer
    Public Property QtyFrom As Decimal
    Public Property QtyTo As Nullable(Of Decimal)
    Public Property FKProductUnit As Integer
    Public Property LotNo As String
    Public Property ProductDate As Date
    Public Property ExpDate As Date
    Public Property ReceiveDate As Date
    Public Property FKItemStatus As Integer
    Public Property OldItemStatus As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property TransferBy As String
    Public Property TransferDate As Nullable(Of Date)
    Public Property PickDate As Nullable(Of Date)
    Public Property RowIDCurrStock As Integer
    Public Property Enable As Boolean

    Public Overridable Property ItemStatus As ItemStatus
    Public Overridable Property Locations As Locations
    Public Overridable Property Products As Products
    Public Overridable Property ProductUnit As ProductUnit
    Public Overridable Property TransferHD As TransferHD

End Class
