'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_GL100AR
    Public Property COCD As String
    Public Property DOCTYPE As String
    Public Property DOCDATE As Date
    Public Property POSTINGDATE As Date
    Public Property POSTINGPERIOD As String
    Public Property CURRENCY As String
    Public Property EXCHANGERATE As String
    Public Property TRANSLATIONDATE As String
    Public Property LEDGERGROUP As String
    Public Property REFERENCE As String
    Public Property DOCHEADERTEXT As String
    Public Property BRANCH As String
    Public Property REFKEYHEAD1 As String
    Public Property REFKEYHEAD2 As String
    Public Property PstKy As String
    Public Property ACCOUNT As String
    Public Property SPECIALGL As String
    Public Property ALTERNATIVEGLACCOUNT As String
    Public Property AMOUNTDOCUMENTCURRENCY As Decimal
    Public Property AMOUNTLOCALCURRENCY As Decimal
    Public Property AMOUNTGROUPCURRENCY As Decimal
    Public Property BUSINESSAREA As String
    Public Property TRADINGPARTNER As String
    Public Property VALUEDATE As String
    Public Property PAYMENTTERM As String
    Public Property BASELINEDATE As String
    Public Property PAYMENTMETHOD As String
    Public Property PAYMENTBLOCK As String
    Public Property INVOICEREFERENCE As String
    Public Property FISCALYEAROFINVOICEREFERNCE As String
    Public Property Qty As Decimal
    Public Property UOM As String
    Public Property ASSIGNMENT As String
    Public Property ITEMTEXT As String
    Public Property TAXCODE As String
    Public Property BUSINESSPLACE As String
    Public Property TAXBASEAMOUNTDOCCURRENCY As String
    Public Property TAXBASEAMOUNTLOCALCURRENCY As String
    Public Property TAXBASEAMOUNTGROUPCURRENCY As String
    Public Property TAXAMOUNTDOCCURRENCY As String
    Public Property TAXAMOUNTLOCALCURRENCY As String
    Public Property TAXAMOUNTGROUPCURRENCY2 As String
    Public Property COSTCENTER As String
    Public Property PROFITCENTER As String
    Public Property INTERNALORDER As String
    Public Property PASEGMENT As String
    Public Property ControllingArea As String
    Public Property Company As String
    Public Property Plant As String
    Public Property BA As String
    Public Property ProfitCenter1 As String
    Public Property Costcenter1 As String
    Public Property CTH1 As String
    Public Property CTH2 As String
    Public Property CTH3 As String
    Public Property CTH4 As String
    Public Property CTH5 As String
    Public Property SalesSup As String
    Public Property SalesRep As String
    Public Property CTH6 As String
    Public Property CTH7 As String
    Public Property CTH8 As String
    Public Property CTH9 As String
    Public Property CTH10 As String
    Public Property CTH11 As String
    Public Property CTH12 As String
    Public Property SalesDistrict As String
    Public Property CTH13 As String
    Public Property CustomerNo As String
    Public Property MatGrp1 As String
    Public Property MatGrp2 As String
    Public Property MatGrp3 As String
    Public Property MatGrp4 As String
    Public Property MatGrp5 As String
    Public Property MatNo As String
    Public Property PDH1 As String
    Public Property PDH2 As String
    Public Property PDH3 As String
    Public Property PDH4 As String
    Public Property PDH5 As String
    Public Property Materialgroup As String
    Public Property ValualtionType As String
    Public Property WTTYPE1 As String
    Public Property WTCODE1 As String
    Public Property WTBASE1DOCCURRENCY As String
    Public Property WTBASE1LOCALCURRENCY As String
    Public Property WTAMT1DOCCURRENCY As String
    Public Property WTAMT1LOCALCURRENCY As String
    Public Property WTTYPE2 As String
    Public Property WTCODE2 As String
    Public Property WTBASE2DOCCURRENCY As String
    Public Property WTBASE2LOCALCURRENCY As String
    Public Property WTAMT2DOCCURRENCY As String
    Public Property WTAMT2LOCALCURRENCY As String
    Public Property ONETIME As String
    Public Property NAME1 As String
    Public Property NAME2 As String
    Public Property NAME3 As String
    Public Property NAME4 As String
    Public Property STREET As String
    Public Property CITY As String
    Public Property POSTALCODE As String
    Public Property LANGUAGEKEY As String
    Public Property COUNTRYKEY As String
    Public Property TAXNUMBER3 As String
    Public Property TYPEOFBUSINESS As String
    Public Property TransDate As String
    Public Property Id As Integer

End Class
