'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_InterfaceOrder
    Public Property Id As Integer
    Public Property HDID As Integer
    Public Property DOCUMENTNO As String
    Public Property DOCUMENTDATE As String
    Public Property DESCRIPTION As String
    Public Property PICKINGTYPECODE As String
    Public Property COMP_CODE As String
    Public Property CUSTOMERCODE As String
    Public Property InterfaceName As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property WAREHOUSECODE As String
    Public Property ITEM_NO As String
    Public Property PRODUCTCODE As String
    Public Property PRODUCTNAME As String
    Public Property PRODUCTQTY As Nullable(Of Decimal)
    Public Property ITEMSTATUSCODE As String
    Public Property PRODUCTUNITCODE As String
    Public Property InterfaceName1 As String
    Public Property CreateDate1 As Nullable(Of Date)
    Public Property CreateBy1 As String
    Public Property UpdateDate1 As Nullable(Of Date)
    Public Property UpdateBy1 As String
    Public Property SRC_NAME As String
    Public Property ItemCate As String
    Public Property Func As String
    Public Property PLANT As String

End Class
