'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_LocationEmpty
    Public Property Id As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property FKCompany As Integer
    Public Property FKZone As Integer
    Public Property FKLocationType As Integer
    Public Property FKWarehouse As Integer
    Public Property InStorage As Boolean
    Public Property Book As String

End Class
