'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_PhyCount
    Public Property Id As Integer
    Public Property DocNo As String
    Public Property DocDate As Date
    Public Property OwnCode As String
    Public Property WHCode As String
    Public Property Description As String
    Public Property ProdCode As String
    Public Property BaseBarcode As String
    Public Property ProdName As String
    Public Property BaseUnitCode As String
    Public Property ItmCode As String
    Public Property Qty As Decimal
    Public Property QtyCount As Decimal
    Public Property QtyDiff As Decimal
    Public Property Remark As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property [CDate] As String
    Public Property FKWarehouse As Integer
    Public Property FKOwner As Integer
    Public Property FKItemStatus As Integer
    Public Property FKProduct As Integer

End Class
