'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_PickLocationSel
    Public Property Id As Integer
    Public Property BatchNo As String
    Public Property CreateDate As Date
    Public Property OwnCode As String
    Public Property WHCode As String
    Public Property ProdCode As String
    Public Property BaseBarcode As String
    Public Property ProdName As String
    Public Property ProductDate As Nullable(Of Date)
    Public Property ExpDate As Nullable(Of Date)
    Public Property ReceiveDate As Nullable(Of Date)
    Public Property ItmCode As String
    Public Property LocName As String
    Public Property Qty As Decimal
    Public Property ZCode As String
    Public Property PickBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property FKCompany As Integer
    Public Property CurStockID As Nullable(Of Integer)
    Public Property FKProduct As Integer

End Class
