'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_PickConfirm
    Public Property Id As Integer
    Public Property OrderNo As String
    Public Property OrderDate As Date
    Public Property BatchNo As String
    Public Property FKCompany As Integer
    Public Property FKOwner As Integer
    Public Property FKCustomer As Integer
    Public Property CustCode As String
    Public Property CustName As String
    Public Property OwnCode As String
    Public Property OwnName As String
    Public Property PickingDate As Date
    Public Property ProdCode As String
    Public Property ProdName As String
    Public Property BaseBarcode As String
    Public Property UnitCode As String
    Public Property PackSize As Decimal
    Public Property Qty As Decimal
    Public Property QtyConfirm As Decimal
    Public Property WHCode As String
    Public Property WHName As String
    Public Property ItmCode As String
    Public Property ItmName As String
    Public Property UDate As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property ODate As String
    Public Property QtyCheck As Decimal

End Class
