'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_PickStatus
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property BatchNo As String
    Public Property FKPickingType As Integer
    Public Property PTypeCode As String
    Public Property PTypeName As String
    Public Property FKOwner As Integer
    Public Property OwnCode As String
    Public Property OwnName As String
    Public Property FKProduct As Integer
    Public Property ProdCode As String
    Public Property ProdName As String
    Public Property FKWarehouse As Integer
    Public Property WHCode As String
    Public Property WHName As String
    Public Property FKItemStatus As Integer
    Public Property ItmCode As String
    Public Property ItmName As String
    Public Property ZCode As String
    Public Property ZName As String
    Public Property FKLocation As Integer
    Public Property LocName As String
    Public Property ProductDate As Nullable(Of Date)
    Public Property ExpDate As Nullable(Of Date)
    Public Property ReceiveDate As Nullable(Of Date)
    Public Property Qty As Decimal
    Public Property AssignDate As Nullable(Of Date)
    Public Property AssingBy As String
    Public Property ConfirmDate As Nullable(Of Date)
    Public Property ConfirmBy As String
    Public Property PickBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property BaseBarcode As String
    Public Property UDate As String

End Class
