'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_PickOrderPosted
    Public Property Id As Integer
    Public Property FKOwner As Integer
    Public Property OrderNo As String
    Public Property OrderDate As Date
    Public Property BatchNo As String
    Public Property OwnCode As String
    Public Property CustCode As String
    Public Property CustName As String
    Public Property PickTypeName As String
    Public Property FKWarehouse As Integer
    Public Property WHCode As String
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateBy As String
    Public Property UpdateDate As Date
    Public Property FKCompany As Integer

End Class
