'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_RcvReport
    Public Property Id As Integer
    Public Property DocumentNo As String
    Public Property DocumentDate As Date
    Public Property ReceiveDate As Nullable(Of Date)
    Public Property TypeCode As String
    Public Property TypeName As String
    Public Property VenCode As String
    Public Property VenName As String
    Public Property OwnCode As String
    Public Property OwnName As String
    Public Property FKCompany As Integer
    Public Property RefNo As String
    Public Property RefDate As Nullable(Of Date)
    Public Property WHCode As String
    Public Property WHName As String
    Public Property UntCode As String
    Public Property ProdCode As String
    Public Property ProdName As String
    Public Property PackSize As Decimal
    Public Property BaseBarcode As String
    Public Property ItmCode As String
    Public Property ItmName As String
    Public Property POITEM As String
    Public Property Quantity As Decimal
    Public Property PriceUnit As Decimal
    Public Property NetPrice As Decimal
    Public Property LotNo As String
    Public Property ProductDate As Date
    Public Property ExpDate As Date
    Public Property DeliveryDate As Nullable(Of Date)
    Public Property RDate As String
    Public Property Remark As String
    Public Property FKWarehouse As Integer
    Public Property CreateDate As Date
    Public Property CreateBy As String
    Public Property UpdateDate As Date
    Public Property UpdateBy As String

End Class
