'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_RPTCycleCount
    Public Property DocNo As String
    Public Property DocDate As Date
    Public Property WHCode As String
    Public Property OwnCode As String
    Public Property LocName As String
    Public Property ProdCode As String
    Public Property ProdName As String
    Public Property ZCode As String
    Public Property ItmCode As String
    Public Property Qty As Decimal
    Public Property QtyCount As Decimal
    Public Property DiffQty As Nullable(Of Decimal)
    Public Property BaseUnitCode As String
    Public Property LotNo As String
    Public Property ProductDate As Date
    Public Property ExpDate As Date
    Public Property ReceiveDate As Date
    Public Property CheckType As String
    Public Property CheckDate As Nullable(Of Date)
    Public Property CheckBy As String
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property BaseBarcode As String

End Class
