'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_RTPPrintInternalBar
    Public Property id As Integer
    Public Property OwnName As String
    Public Property ProdCode As String
    Public Property Barcode As String
    Public Property ProductName As String
    Public Property cnt As Nullable(Of Integer)
    Public Property Code As String
    Public Property CreateDate As String
    Public Property CreateBy As String
    Public Property FKCompany As Integer

End Class
