'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_StockBal
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property FKProduct As Integer
    Public Property WHCode As String
    Public Property OwnCode As String
    Public Property ProdCode As String
    Public Property ProdName As String
    Public Property ZCode As String
    Public Property ZName As String
    Public Property ItmCode As String
    Public Property ItmName As String
    Public Property Qty As Decimal
    Public Property BookQty As Decimal
    Public Property QtyCost As Decimal
    Public Property NetPrice As Decimal
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property UntCode As String
    Public Property BaseBarcode As String
    Public Property FKWarehouse As Integer
    Public Property FKOwner As Integer

End Class
