'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_StockCard
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property FKProduct As Integer
    Public Property OwnCode As String
    Public Property WHCode As String
    Public Property TransactionDate As Date
    Public Property DocNo As String
    Public Property DocDate As Date
    Public Property Reference As String
    Public Property Description As String
    Public Property ProdCode As String
    Public Property ProdName As String
    Public Property ZCode As String
    Public Property ZName As String
    Public Property ItmCode As String
    Public Property ItmName As String
    Public Property InQty As Decimal
    Public Property InCost As Decimal
    Public Property InValue As Decimal
    Public Property OutQty As Decimal
    Public Property OutCost As Decimal
    Public Property OutValue As Decimal
    Public Property BalQty As Decimal
    Public Property BalCost As Decimal
    Public Property BalValue As Decimal
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property UntCode As String
    Public Property BaseBarcode As String
    Public Property TDate As String
    Public Property FKWarehouse As Integer
    Public Property FKOwner As Integer

End Class
