'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_StockLocation
    Public Property Vendor As String
    Public Property Owners As String
    Public Property Material_Description As String
    Public Property Material_Type As String
    Public Property Qty As Decimal
    Public Property Location As String
    Public Property Location_Type As String
    Public Property Warehouse As String
    Public Property Material_Code As String
    Public Property Item_Status As String
    Public Property Zone As String
    Public Property ReceiveDate As Date
    Public Property ProductDate As Date
    Public Property Expire_Date As Date
    Public Property WHCode As String
    Public Property LocTypeCode As String
    Public Property BaseUnitCode As String
    Public Property OwnCode As String
    Public Property ItemStatCode As String
    Public Property VenCode As String
    Public Property ProdTypeCode As String
    Public Property ZCode As String
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property LotNo As String
    Public Property BookQty As Decimal
    Public Property PriceUnit As Decimal
    Public Property NetPrice As Decimal
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property BaseBarcode As String
    Public Property FKOwner As Integer
    Public Property FKWarehouse As Integer

End Class
