'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_TransferConfirm
    Public Property Id As Integer
    Public Property FKCompany As Integer
    Public Property FKWarehouse As Integer
    Public Property DocNo As String
    Public Property DocDate As Date
    Public Property WHCode As String
    Public Property ProdCode As String
    Public Property ProdName As String
    Public Property OldItemStatus As String
    Public Property ZCode As String
    Public Property LocName As String
    Public Property LocationTo As String
    Public Property ItmCode As String
    Public Property QtyFrom As Decimal
    Public Property LotNo As String
    Public Property ProductDate As Date
    Public Property ExpDate As Date
    Public Property ReceiveDate As Date
    Public Property FKItemStatus As Integer
    Public Property UpdateDate As Date
    Public Property UpdateBy As String
    Public Property RowIDCurrStock As Integer
    Public Property BaseBarcode As String

End Class
